export enum UserStatus {
    INVITED = 'INVITED',
    REGISTERED = 'REGISTERED',
    NEED_CONFIRMATION = 'NEED_CONFIRMATION',
    CONFIRMED = 'CONFIRMED',
    ACTIVE = 'ACTIVE',
    NOT_ACTIVE = 'NOT_ACTIVE'
}
