version: '3.2'

services:
  app:
    image: registry.n-t.io/karma/hlf-explorer/hlf-explorer:${TAG:-master}
    env_file:
      - ./dev.env
    volumes:
      - ./:/app:cached
    depends_on:
      - db
    ports:
      - 33000:3000
    working_dir: /app
    command: npm run start:dev
    networks:
      - default
      - ledger

  db:
    image: postgres:11.4-alpine
    env_file:
      - ./dev.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 35432:5432
    networks:
      - default
      - ledger

volumes:
  pg_data:

networks:
  ledger:
    external:
      name: karma-ledger_basic
