{{ $assignPodsToNodes := include "karma.assignPodsToNodes" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "werf.io/track": "true"
spec:
  activeDeadlineSeconds: 7200
  ttlSecondsAfterFinished: 604800
  backoffLimit: 3
  template:
    metadata:
      name: {{ .Chart.Name }}-migrations
    spec:
{{ $assignPodsToNodes }}
      imagePullSecrets:
        - name: {{ required "$.Values.registry.secret_name" $.Values.registry.secret_name }}
      restartPolicy: Never
      containers:
      - name: db-update
{{ tuple "hlf-explorer" . | include "werf_container_image" | indent 8 }}
        command: ["/bin/sh","-c", "-l", "npm run migration:run"]
        workingDir: /app/dist
        env:
{{ tuple "hlf-explorer" . | include "werf_container_env" | indent 8 }}
{{ include "hlf-explorer-envs" . | indent 8 }}
